export const steps = [
  {
    dateStart: '2022-09-01',
    dateEnd: '',
    title: 'Freelancer',
    subTitle: 'FullStack developer',
    description: `As a front-end developer, I organize the project using the scrum methodology. I use a github and a his board with issues to keep everything organized.`,
    logo: '',
  },
  {
    dateStart: '2021-07-01',
    dateEnd: '2022-09-02',
    title: '🐻BearStudio',
    subTitle: 'FullTime developer',
    description: `Competent in dealing with JavaScript, React, Chakra-UI, React-query, and Cypress, React JS and React native project builds web and mobile applications from Figma mock-ups with high and responsive details.`,
    logo: '',
  },
  {
    dateStart: '2021-02-01',
    dateEnd: '2021-06-02',
    title: 'VINTONET',
    subTitle: 'Full Stack Developer (stage)',
    description: `Design and creation of a project: Web and mobile tools for operating medical practices (Laravel & React).
    https://github.com/khannoussi-malek/tbiby`,
    isGalleryExist: false,
    gallery: [],
    logo: '',
  },
  {
    dateStart: '2020-06-01',
    dateEnd: '2020-09-02',
    title: 'VINTONET',
    subTitle: 'web and mobile development (stage)',
    description: 'Construction of a Marketplace (Laravel)',
    isGalleryExist: false,
    gallery: [],
    logo: '',
  },
  {
    dateStart: '2020-01-01',
    dateEnd: '2020-02-02',
    title: 'Dev Tweaks',
    subTitle: 'Full Stack Developer (stage)',
    description:
      'Web and mobile application development for NCR: project conception and development',
    isGalleryExist: false,
    gallery: [],
    logo: '',
  },
  {
    dateStart: '2019-08-01',
    dateEnd: '2019-09-02',
    title: 'VINTONET',
    subTitle: 'Full Stack Developer (stage)',
    description:
      'Creation of websites for particular brands, such as Yamaha (motorcycles).',
    isGalleryExist: false,
    gallery: [],
    logo: '',
  },
];
